version: '3'

services: 
  target_1:
    build:
      context: .
      dockerfile: target.Dockerfile
  target_2:
    build:
      context: .
      dockerfile: target.Dockerfile
    depends_on:
      - "target_1"
  splitter:
    build:
      context: .
      dockerfile: splitter.Dockerfile
    depends_on:
      - "target_2"
  agent:
    build:
      context: .
      dockerfile: agent.Dockerfile
    depends_on:
      - "splitter"
