name: Data Distribution

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  deployment:
    
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
  
      - uses: actions/checkout@v2

      # Create temporary directory where we can collect log outputs
      - run: mkdir outputs

      # Runs a set of commands using the runners shell
      - name: Start up docker containers
        run: |
          docker-compose -f "docker-compose.yml" up -d --build
          docker ps
      
      # Copy event logs from running container to temp directory
      - name: Save log files from target 1 and target 2
        run: |
          docker ps
          docker cp cribl_target_1_1:/usr/src/events.log /home/runner/work/cribl/cribl/outputs/events_target_1.log
          docker cp cribl_target_2_1:/usr/src/events.log /home/runner/work/cribl/cribl/outputs/events_target_2.log
      
      # Upload artifacts from temp directory
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: my-artifact
          path: /home/runner/work/cribl/cribl/outputs/*
      
      # This step will remove containers after each run even on failed deployment
      - name: Remove containers after the run
        if: always()
        run: docker-compose -f "docker-compose.yml" down
  
  testing:
    # This job depebds on successful deployment job
    needs: deployment
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      # Create temp directory to download artifacts so test framework can process them
      - run: mkdir outputs
      
      # Download artifacts to temp directory
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: /home/runner/work/cribl/cribl/outputs
      
      # Set up Python for test framework
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      # Install dependencies from requirements.txt file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Collect all tests using pytest command
      - name: Test with Pytest
        run: |
          pytest -v --html=test_report.html --self-contained-html
        
      # Upload test results report html file to pipeline artifacts
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: my-artifact
          path: /home/runner/work/cribl/cribl/test_report.html
